version: 2
update_configs:
  - package-ecosystem: "java:maven"
    directory: "/"
    schedule:
      interval: weekly
      time: '04:00'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: '05:00'
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/package"
    schedule:
      interval: weekly
      time: '06:00'
    open-pull-requests-limit: 10
