name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11

    - name: Deploy
      run: mvn deploy -PnoServerTest --batch-mode --quiet --errors --fail-at-end --show-version  --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

